repos:
-   repo: local
    hooks:
    -   id: black
        name: black
        args: [--config, pyproject.toml]
        entry: black --check .
        language: system
        types: [python]
        pass_filenames: false
    -   id: flake8
        name: flake8
        entry: flake8 .
        language: system
        types: [python]
        pass_filenames: false
    -   id: isort
        name: isort
        args: [--settings-path, pyproject.toml]
        entry: isort --check .
        language: system
        types: [python]
        pass_filenames: false
