[tool.black]
line-length = 79
target-version = ['py310']
include = '\.pyi?$'

[tool.isort]
profile = "black"
line_length = 79

[tool.mypy]
python_version = '3.10'
plugins = [
    'mypy_django_plugin.main',
    'mypy_drf_plugin.main'
]
mypy_path = 'src'
exclude = [
    'migrations',
]
follow_imports = 'silent'
warn_redundant_casts = true
warn_unused_ignores = true
show_error_codes = true
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = []
ignore_missing_imports = true

[tool.django-stubs]
django_settings_module = "config.settings"

