# Generated by Django 4.1.5 on 2023-01-13 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_managers"),
        (
            "users",
            "0002_alter_user_managers_user_groups_user_is_superuser_and_more",
        ),
    ]

    operations = []
