# Generated by Django 4.1.5 on 2023-01-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_merge_20230113_0804"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("user", "User"),
                    ("manager", "Manager"),
                ],
                max_length=10,
            ),
        ),
    ]
